In [ ]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files

uploaded = files.upload()

Saving WA_Fn-UseC_-Telco-Customer-Churn.csv to WA_Fn-UseC_-Telco-Customer-Churn.csv

In [ ]:

import io

file_name = next(iter(uploaded))

df = pd.read_csv(io.BytesIO(uploaded[file_name]))

print("Dataset loaded successfully.")
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

df.head()

Dataset loaded successfully.
Number of rows: 7043
Number of columns: 21

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [ ]:

print("Dataset dimensions:", df.shape)

print("\nColumn names:")
print(df.columns.tolist())

print("\nData types and non-null counts:")
df.info()

print("\nFirst 5 records:")
display(df.head())

print("\nSummary of numerical columns:")
display(df.describe())

Dataset dimensions: (7043, 21)

Column names:
['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn']

Data types and non-null counts:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

First 5 records:

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

Summary of numerical columns:

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [ ]:
# STEP 2: DATA QUALITY AUDIT

print("Missing values:")
display(df.isnull().sum().sort_values(ascending=False))

print("\nDuplicate rows:")
print(df.duplicated().sum())

print("\nUnique values in TotalCharges:")
print("TotalCharges dtype:", df["TotalCharges"].dtype)
print("Blank/empty values:", (df["TotalCharges"].astype(str).str.strip() == "").sum())

print("\nChurn distribution:")
display(df["Churn"].value_counts())

print("\nChurn percentage:")
display(df["Churn"].value_counts(normalize=True).mul(100).round(2))

print("\nUnique values in SeniorCitizen:")
print(df["SeniorCitizen"].unique())

print("\nUnique values in Contract:")
print(df["Contract"].unique())

print("\nUnique values in PaymentMethod:")
print(df["PaymentMethod"].unique())

Missing values:

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

Duplicate rows:
0

Unique values in TotalCharges:
TotalCharges dtype: object
Blank/empty values: 11

Churn distribution:

Churn
No     5174
Yes    1869
Name: count, dtype: int64

Churn percentage:

Churn
No     73.46
Yes    26.54
Name: proportion, dtype: float64

Unique values in SeniorCitizen:
[0 1]

Unique values in Contract:
['Month-to-month' 'One year' 'Two year']

Unique values in PaymentMethod:
['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']

In [ ]:
# STEP 3: INVESTIGATE BLANK TOTAL CHARGES

blank_total = df[df["TotalCharges"].astype(str).str.strip() == ""]

print("Number of blank TotalCharges records:", len(blank_total))

display(
    blank_total[
        [
            "customerID",
            "tenure",
            "MonthlyCharges",
            "Contract",
            "PaymentMethod",
            "Churn"
        ]
    ]
)

Number of blank TotalCharges records: 11

,customerID,tenure,MonthlyCharges,Contract,PaymentMethod,Churn
488,4472-LVYGI,0,52.55,Two year,Bank transfer (automatic),No
753,3115-CZMZD,0,20.25,Two year,Mailed check,No
936,5709-LVOEQ,0,80.85,Two year,Mailed check,No
1082,4367-NUYAO,0,25.75,Two year,Mailed check,No
1340,1371-DWPAZ,0,56.05,Two year,Credit card (automatic),No
3331,7644-OMVMY,0,19.85,Two year,Mailed check,No
3826,3213-VVOLG,0,25.35,Two year,Mailed check,No
4380,2520-SGTTA,0,20.00,Two year,Mailed check,No
5218,2923-ARZLG,0,19.70,One year,Mailed check,No
6670,4075-WKNIU,0,73.35,Two year,Mailed check,No
6754,2775-SEFEE,0,61.90,Two year,Bank transfer (automatic),No

In [ ]:
# STEP 4: CLEAN TOTAL CHARGES

# Convert blank strings to NaN
df["TotalCharges"] = df["TotalCharges"].replace(r"^\s*$", np.nan, regex=True)

# Convert TotalCharges to numeric
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")

# Fill the 11 blank TotalCharges values with 0
# Reason: all affected customers have tenure = 0
df.loc[df["TotalCharges"].isna() & (df["tenure"] == 0), "TotalCharges"] = 0

print("Remaining missing TotalCharges:", df["TotalCharges"].isna().sum())
print("TotalCharges dtype:", df["TotalCharges"].dtype)

display(df[["tenure", "MonthlyCharges", "TotalCharges"]].head())

Remaining missing TotalCharges: 0
TotalCharges dtype: float64

   tenure  MonthlyCharges  TotalCharges
0       1           29.85         29.85
1      34           56.95       1889.50
2       2           53.85        108.15
3      45           42.30       1840.75
4       2           70.70        151.65

In [ ]:
# STEP 5: VALIDATE TOTAL CHARGES

print("Customers with tenure = 0:")
display(
    df[df["tenure"] == 0][
        ["customerID", "tenure", "MonthlyCharges", "TotalCharges", "Churn"]
    ]
)

print("\nTotal customers with tenure = 0:", (df["tenure"] == 0).sum())

print("\nTotalCharges summary:")
display(df["TotalCharges"].describe())

Customers with tenure = 0:

      customerID  tenure  MonthlyCharges  TotalCharges Churn
488   4472-LVYGI       0           52.55           0.0    No
753   3115-CZMZD       0           20.25           0.0    No
936   5709-LVOEQ       0           80.85           0.0    No
1082  4367-NUYAO       0           25.75           0.0    No
1340  1371-DWPAZ       0           56.05           0.0    No
3331  7644-OMVMY       0           19.85           0.0    No
3826  3213-VVOLG       0           25.35           0.0    No
4380  2520-SGTTA       0           20.00           0.0    No
5218  2923-ARZLG       0           19.70           0.0    No
6670  4075-WKNIU       0           73.35           0.0    No
6754  2775-SEFEE       0           61.90           0.0    No

Total customers with tenure = 0: 11

TotalCharges summary:

count    7043.000000
mean     2279.734304
std      2266.794470
min         0.000000
25%       398.550000
50%      1394.550000
75%      3786.600000
max      8684.800000
Name: TotalCharges, dtype: float64

In [ ]:
# STEP 6: CREATE TENURE BAND

df["TenureBand"] = pd.cut(
    df["tenure"],
    bins=[-1, 12, 24, 48, float("inf")],
    labels=["0-12 Months", "13-24 Months", "25-48 Months", "49+ Months"]
)

print("Tenure bands created successfully.")

display(
    df[["tenure", "TenureBand"]].head(10)
)

print("\nCustomers in each tenure band:")
display(df["TenureBand"].value_counts().sort_index())

Tenure bands created successfully.

   tenure    TenureBand
0       1   0-12 Months
1      34  25-48 Months
2       2   0-12 Months
3      45  25-48 Months
4       2   0-12 Months
5       8   0-12 Months
6      22  13-24 Months
7      10   0-12 Months
8      28  25-48 Months
9      62    49+ Months

Customers in each tenure band:

TenureBand
0-12 Months     2186
13-24 Months    1024
25-48 Months    1594
49+ Months      2239
Name: count, dtype: int64

In [ ]:
# STEP 7: CREATE BUSINESS-FRIENDLY FIELDS

# Churn flag: 1 = Churned, 0 = Retained
df["ChurnFlag"] = df["Churn"].map({"Yes": 1, "No": 0})

# Monthly charge bands
df["MonthlyChargeBand"] = pd.cut(
    df["MonthlyCharges"],
    bins=[-1, 30, 60, 90, float("inf")],
    labels=["Low (≤30)", "Medium (31-60)", "High (61-90)", "Very High (>90)"]
)

print("Business fields created successfully.")

display(
    df[
        [
            "MonthlyCharges",
            "MonthlyChargeBand",
            "Churn",
            "ChurnFlag"
        ]
    ].head(10)
)

print("\nChurnFlag distribution:")
display(df["ChurnFlag"].value_counts())

print("\nMonthly charge band distribution:")
display(df["MonthlyChargeBand"].value_counts().sort_index())

Business fields created successfully.

   MonthlyCharges MonthlyChargeBand Churn  ChurnFlag
0           29.85         Low (≤30)    No          0
1           56.95    Medium (31-60)    No          0
2           53.85    Medium (31-60)   Yes          1
3           42.30    Medium (31-60)    No          0
4           70.70      High (61-90)   Yes          1
5           99.65   Very High (>90)   Yes          1
6           89.10      High (61-90)    No          0
7           29.75         Low (≤30)    No          0
8          104.80   Very High (>90)   Yes          1
9           56.15    Medium (31-60)    No          0

ChurnFlag distribution:

ChurnFlag
0    5174
1    1869
Name: count, dtype: int64

Monthly charge band distribution:

MonthlyChargeBand
Low (≤30)          1653
Medium (31-60)     1265
High (61-90)       2386
Very High (>90)    1739
Name: count, dtype: int64

In [ ]:
# STEP 8: FINAL VALIDATION

print("FINAL DATASET CHECK")
print("-" * 40)

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

print("\nMissing values:")
print(df.isnull().sum().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())

print("\nData types:")
print(df[["TotalCharges", "tenure", "MonthlyCharges", "ChurnFlag"]].dtypes)

print("\nFinal columns:")
print(df.columns.tolist())

FINAL DATASET CHECK
----------------------------------------
Rows: 7043
Columns: 24

Missing values:
0

Duplicate rows:
0

Data types:
TotalCharges      float64
tenure              int64
MonthlyCharges    float64
ChurnFlag           int64
dtype: object

Final columns:
['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn', 'TenureBand', 'ChurnFlag', 'MonthlyChargeBand']

In [ ]:
# EXPORT CLEANED DATASET FOR EXCEL

output_file = "Telecom_Customer_Retention_Analytics.xlsx"

df.to_excel(output_file, index=False)

print(f"File exported successfully: {output_file}")

File exported successfully: Telecom_Customer_Retention_Analytics.xlsx